# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install jemalloc graphviz
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Run benchmark
      run: swift package --allow-writing-to-package-directory benchmark --format jmh
